# Generated by Django 5.2.5 on 2025-09-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_post_user_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='likes',
        ),
    ]
