# Generated by Django 5.2.5 on 2025-09-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_image',
            field=models.CharField(null=True),
        ),
    ]
