# Generated by Django 5.2.5 on 2025-09-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_post_post_image_alter_reply_reply_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_image',
            field=models.ImageField(null=True, upload_to='reply_images/'),
        ),
    ]
