# Generated by Django 5.2.5 on 2025-09-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_post_post_image_alter_reply_reply_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table='like',
        ),
    ]
