# Generated by Django 5.2.5 on 2025-09-02 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_like_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table='like_table',
        ),
    ]
