# Generated by Django 5.2.5 on 2025-09-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_post_post_image_alter_reply_reply_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
