# Generated by Django 5.2.5 on 2025-09-05 09:53

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_post_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=django_quill.fields.QuillField(),
        ),
    ]
