# Generated by Django 5.2.5 on 2025-09-05 10:46

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_post_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=django_quill.fields.QuillField(default=''),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_content',
            field=django_quill.fields.QuillField(default=''),
        ),
    ]
