# Generated by Django 5.2.5 on 2025-09-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_post_post_content_alter_reply_reply_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_content',
            field=models.TextField(blank=True),
        ),
    ]
